trigger:
  none

pool:
 name: akspool01
 demands:
   - agent.name -equals aksagent01


stages:
  - stage: aks_deployment
    displayName: "aks_deployment"
    jobs:
      - job: aks_deployment
        steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: 'AKS_TO_pipeline'
            azureResourceGroup: 'aks-grp'
            kubernetesCluster: 'aks-cluster'
            namespace: 'default'
            manifests: 'release/kubernetes-manifests.yaml'