trigger:
  - main

pool:
 name: aks01-pool
 demands:
   - agent.name -equals aks-agent01


stages:
  - stage: aks_deployment1
    displayName: "aks_deployment1"
    jobs:
      - job: aks_deployment1
        steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'aks-conn'
            namespace: 'kumar-ns'
            manifests: 'release/kubernetes-manifests.yaml'