trigger:
  - main

pool:
 name: aks01-pool
 demands:
   - agent.name -equals aks-agent01


stages:
  - stage: aks_deployment
    displayName: "aks_deployment"
    jobs:
      - job: aks_deployment
        steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: 'aks-conn'
            azureResourceGroup: 'aks-grp'
            kubernetesCluster: 'aks-cluster'
            namespace: 'default'
            manifests: 'release/kubernetes-manifests.yaml'